server:
  port: 8001

api:
  keys:
    document-service: your-document-service-key
    writer-service: your-writer-service-key

spring:
  application:
    name: auth

  security:
    user:
      name: admin
      password: admin

#    datasource:
#      url: jdbc:h2:mem:testdb
#      driver-class-name: org.h2.Driver
#      username: myuser
#      password: mypassword
#    h2:
#      console:
#        enabled: true
#        path: /h2-console
#    jpa:
#      hibernate:
#        ddl-auto: update
#      show-sql: true

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/TEMP?autoReconnect=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:naman}

eureka:
  instance:
    prefer-ip-address: true 
  client:
    service-url:
      defaultZone: http://${EUREKA_URL:localhost:8761}/eureka/




#logging:
#  level:
#    org: DEBUG