server:
  port: 8001

spring:
  application:
    name: auth

  security:
    user:
      name: admin
      password: admin

  datasource:
    url: jdbc:mysql://localhost:3306/TEMP
    username: root
    password: naman


eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



#logging:
#  level:
#    org: DEBUG