spring:
  application:
    name: gateway

  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: AUTH
          uri: lb://AUTH
          predicates:
            - Path=/auth/**
        - id: READER
          uri: lb://READER
          predicates:
            - Path=/reader/**
        - id: WRITER
          uri: lb://WRITER
          predicates:
            - Path=/writer/**

server:
  port: 8080

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
