spring:
  application:
    name: reader

server:
  port: 8082

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
